# YAML YML 配置文件，环境变量 ${}  -DskipTests -D.skip.test 会读Jar 同级的配置文件，且比内部更要优先 命令行参数也可以 17种优先级，尽量避免优先级

#所有环境公用的配置属性

# 显示health 的所有信息
#management.endpoint.health.show-details=always
management:
  endpoint:
    health:
      show-details: always
  # 激活所有的端点， 默认只有info 和health configprops
  #/metrics/name（key端点查看对应的信息）
  #management.endpoints.web.exposure.include=*
  endpoints:
    web:
      exposure:
        include: '*'
#默认启动
spring:
  profiles:
    active: dev
  application:
    name: quick-service-provider
 # cloud:
  #  nacos:
   #  discovery:
     #   server-addr: 127.0.0.1:8848
#info. key 和value形式

#连字符
---

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://101.37.81.92:3306/xir
    hikari:
      username: root
      password: zhangyu110
      #>=6.x com.mysql.cj.jdbc.Driver
      #<=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: b4826df8-24e5-4472-9e77-78ab775e160e
        cluster-name: firstCluster
        metadata:
          mykey: myvalue
# profile=dev专用属性，也就是某个环境下的专用属性
#比如开发
server:
  port: 8009
---
spring:
  profiles: product1
  datasource:
    url: jdbc:mysql://101.37.81.92:3306/xir
    hikari:
      username: root
      password: zhangyu110
      #>=6.x com.mysql.cj.jdbc.Driver
      #<=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: b4826df8-24e5-4472-9e77-78ab775e160e
        cluster-name: twoCluster
#profile=product 的专用属性
server:
  port: 8010
---
spring:
  profiles: product2
  datasource:
    url: jdbc:mysql://101.37.81.92:3306/xir
    hikari:
      username: root
      password: zhangyu110
      #>=6.x com.mysql.cj.jdbc.Driver
      #<=5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: b4826df8-24e5-4472-9e77-78ab775e160e
        cluster-name: twoCluster
#profile=product 的专用属性
server:
  port: 8011