spring:
  profiles:
    active: dev
  application:
    name: alii-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 让gateway 通过服务发现找其他服务
    gateway:
      discovery:
        locator:
          enabled: true


---
# 显示health 的所有信息
# management.endpoint.health.show-details=always
management:
  endpoint:
    health:
      show-details: always
  # 激活所有的端点， 默认只有info 和health configprops
  # /metrics/name（key端点查看对应的信息）
  # management.endpoints.web.exposure.include=*
  endpoints:
    web:
      exposure:
        include: '*'
server:
  port: 9876
spring:
  profiles: dev
